name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
version: 0.10.6

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.5"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android: ^0.10.9
  camera_avfoundation: ^0.9.13
  camera_platform_interface: ^2.6.0
  camera_web: ^0.3.3
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  plugin_platform_interface: ^2.1.7

topics:
  - camera
